// Generates draft-farley-acta-signed-receipts-02 conformant fixtures for the
// TRACE action-receipts crosswalk.
//
// Conformance points (verified against the published draft-02 text):
//   - Envelope (s2.1): { payload, signature: { alg, kid, sig } }
//   - alg "EdDSA" (MTI, s2.1.1); sig = 128 lowercase hex chars
//   - kid RECOMMENDED format sb:issuer:<first 12 Base58 chars of pubkey> (s2.1.1)
//   - payload common fields type / issued_at / issuer_id, with issuer_id
//     REQUIRED to match signature.kid (s2.2)
//   - Access-decision payload (s3.1): type "protectmcp:decision", tool_name,
//     decision (allow|deny|rate_limit), reason, policy_digest "sha256:<hex>",
//     session_id (opaque, non-correlatable)
//   - Signature scope (s5.6): PureEdDSA directly over JCS bytes of payload,
//     no pre-hash
//   - Chain hash scope (s5.7): previousReceiptHash = bare lowercase hex of
//     SHA-256(JCS(entire signed envelope INCLUDING signature))
//
// Every fixture is generated by real signing, then SELF-CHECKED against the
// expectations in expected.json before being written; generation aborts on
// any mismatch. Negative fixtures are deterministic committed artifacts, not
// transient states inside this script.
import { ed25519 } from '@noble/curves/ed25519.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { writeFileSync, mkdirSync } from 'node:fs';

const bytesToHex = (b) => Buffer.from(b).toString('hex');
const hexToBytes = (h) => new Uint8Array(Buffer.from(h, 'hex'));

// Minimal JCS (RFC 8785) for the ASCII-only content in these fixtures.
function canonicalize(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`;
  const keys = Object.keys(value).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalize(value[k])}`).join(',')}}`;
}
const canonicalBytes = (obj) => new TextEncoder().encode(canonicalize(obj));
const sha256hex = (bytes) => bytesToHex(sha256(bytes));

// Base58 (Bitcoin alphabet), for the s2.1.1 RECOMMENDED kid format.
const B58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function base58(bytes) {
  let n = BigInt('0x' + bytesToHex(bytes));
  let out = '';
  while (n > 0n) { out = B58[Number(n % 58n)] + out; n /= 58n; }
  for (const b of bytes) { if (b === 0) out = '1' + out; else break; }
  return out;
}

// --- Deterministic keypairs ---
// Signer (same seed as the previously published signer-public-key.txt).
const SIGNER_PRIV = '4c9c9f6a5b2e7d3f1a8b6c4d2e9f7a1b3c5d7e9f1a2b4c6d8e0f2a4b6c8d0e1f';
const SIGNER_PUB = bytesToHex(ed25519.getPublicKey(hexToBytes(SIGNER_PRIV)));
// A second real key, used ONLY to produce the committed key-mismatch fixture.
const MISMATCH_PRIV = 'e1d2c3b4a5968778695a4b3c2d1e0f00112233445566778899aabbccddeeff10';
const MISMATCH_PUB = bytesToHex(ed25519.getPublicKey(hexToBytes(MISMATCH_PRIV)));

const KID = `sb:issuer:${base58(hexToBytes(SIGNER_PUB)).slice(0, 12)}`;

// Real digests over actual (illustrative) policy bundle bytes.
const POLICY_V1 = `sha256:${sha256hex(canonicalBytes({ policy: 'permit read-only; forbid destructive', rev: 1 }))}`;
const POLICY_V2 = `sha256:${sha256hex(canonicalBytes({ policy: 'permit read-only; forbid destructive; forbid network-egress', rev: 2 }))}`;

const SESSION = 'ses_8f31ab';         // the session fixtures 01/02/04/05 belong to
const OTHER_SESSION = 'ses_2c91d4';   // a different, equally opaque session

function envelope(payload, privHex) {
  const sig = bytesToHex(ed25519.sign(canonicalBytes(payload), hexToBytes(privHex)));
  return { payload, signature: { alg: 'EdDSA', kid: KID, sig } };
}
// s5.7: chain hash covers the ENTIRE envelope, signature included.
const envelopeHash = (env) => sha256hex(canonicalBytes(env));

function decisionPayload({ tool, decision, reason, sessionId, issuedAt, prevHash, policyDigest = POLICY_V2 }) {
  const p = {
    type: 'protectmcp:decision',
    tool_name: tool,
    decision,
    policy_digest: policyDigest,
    session_id: sessionId,
    issued_at: issuedAt,
    issuer_id: KID,
  };
  if (reason) p.reason = reason;
  if (prevHash) p.previousReceiptHash = prevHash;
  return p;
}

// --- Build the six fixtures ---
const r01 = envelope(decisionPayload({
  tool: 'run_shell', decision: 'allow', sessionId: SESSION,
  issuedAt: '2026-07-08T09:00:01.000Z',
}), SIGNER_PRIV);

const r02 = envelope(decisionPayload({
  tool: 'delete_database', decision: 'deny', reason: 'policy_block',
  sessionId: SESSION, issuedAt: '2026-07-08T09:00:05.000Z',
  prevHash: envelopeHash(r01),
}), SIGNER_PRIV);

// 03: identical payload shape to 01 but signed by a DIFFERENT real key while
// still claiming the signer's kid. Resolving kid to the published signer key
// deterministically fails verification. Both public keys are committed.
const r03 = envelope(decisionPayload({
  tool: 'run_shell', decision: 'allow', sessionId: SESSION,
  issuedAt: '2026-07-08T09:00:01.000Z',
}), MISMATCH_PRIV);

// 04: VALIDLY SIGNED by the signer, but previousReceiptHash points at r01's
// envelope hash when the actual predecessor in the fixture chain is r02.
// Signature verification passes; the chain-link recomputation fails.
const r04 = envelope(decisionPayload({
  tool: 'read_file', decision: 'allow', sessionId: SESSION,
  issuedAt: '2026-07-08T09:00:09.000Z',
  prevHash: envelopeHash(r01), // wrong on purpose: true predecessor is r02
}), SIGNER_PRIV);

// 05: validly signed, but policy_digest is the v1 policy while the policy in
// force at verification time (per expected.json) is v2. Signature passes;
// the freshness check fails.
const r05 = envelope(decisionPayload({
  tool: 'run_shell', decision: 'allow', sessionId: SESSION,
  issuedAt: '2026-07-08T09:00:12.000Z',
  policyDigest: POLICY_V1, // the only fixture carrying the superseded policy
}), SIGNER_PRIV);

// 06: validly signed, but bound to a different session than the one the
// verifier expects (per expected.json). Signature passes; binding fails.
const r06 = envelope(decisionPayload({
  tool: 'run_shell', decision: 'allow', sessionId: OTHER_SESSION,
  issuedAt: '2026-07-07T14:30:02.000Z',
}), SIGNER_PRIV);

const fixtures = {
  '01-valid-accepted.json': r01,
  '02-valid-denied.json': r02,
  '03-signature-key-mismatch.json': r03,
  '04-broken-chain.json': r04,
  '05-stale-policy-digest.json': r05,
  '06-session-binding-mismatch.json': r06,
};

// Machine-readable expectations, consumed by tests/test_acta_fixtures.py.
const expected = {
  signer_public_key_hex: SIGNER_PUB,
  current_policy_digest: POLICY_V2,
  expected_session_id: SESSION,
  chain: { '02-valid-denied.json': '01-valid-accepted.json', '04-broken-chain.json': '02-valid-denied.json' },
  results: {
    '01-valid-accepted.json':          { signature: 'pass', chain: 'n/a',  policy_freshness: 'pass', session_binding: 'pass' },
    '02-valid-denied.json':            { signature: 'pass', chain: 'pass', policy_freshness: 'pass', session_binding: 'pass' },
    '03-signature-key-mismatch.json':  { signature: 'fail', chain: 'n/a',  policy_freshness: 'n/a',  session_binding: 'n/a' },
    '04-broken-chain.json':            { signature: 'pass', chain: 'fail', policy_freshness: 'pass', session_binding: 'pass' },
    '05-stale-policy-digest.json':     { signature: 'pass', chain: 'n/a',  policy_freshness: 'fail', session_binding: 'pass' },
    '06-session-binding-mismatch.json':{ signature: 'pass', chain: 'n/a',  policy_freshness: 'pass', session_binding: 'fail' },
  },
};

// --- Self-check every fixture against the manifest before writing ---
const verifySig = (env, pubHex) => {
  try { return ed25519.verify(hexToBytes(env.signature.sig), canonicalBytes(env.payload), hexToBytes(pubHex)); }
  catch { return false; }
};
let failures = 0;
for (const [name, env] of Object.entries(fixtures)) {
  const exp = expected.results[name];
  const sig = verifySig(env, SIGNER_PUB) ? 'pass' : 'fail';
  let ok = sig === exp.signature;
  let chain = 'n/a';
  if (expected.chain[name]) {
    const pred = fixtures[expected.chain[name]];
    chain = env.payload.previousReceiptHash === envelopeHash(pred) ? 'pass' : 'fail';
    ok = ok && chain === exp.chain;
  }
  // structural conformance
  ok = ok && env.signature.alg === 'EdDSA'
          && /^[0-9a-f]{128}$/.test(env.signature.sig)
          && env.payload.issuer_id === env.signature.kid
          && env.payload.type === 'protectmcp:decision'
          && ['allow', 'deny', 'rate_limit'].includes(env.payload.decision);
  console.log(`${name}: signature=${sig} chain=${chain} structural=${ok ? 'ok' : 'BAD'}`);
  if (!ok) failures++;
}
// Freshness and binding are checked for EVERY fixture against the manifest, not
// only for the two that are meant to fail them. Asserting the failure alone
// passes whether one fixture is stale or all six are, which is how every fixture
// came to carry the same policy_digest while four were declared to pass.
for (const [name, env] of Object.entries(fixtures)) {
  const exp = expected.results[name];
  for (const [axis, actual] of [
    ['policy_freshness', env.payload.policy_digest === expected.current_policy_digest ? 'pass' : 'fail'],
    ['session_binding', env.payload.session_id === expected.expected_session_id ? 'pass' : 'fail'],
  ]) {
    if (exp[axis] === 'n/a') continue;   // 03 fails signature; nothing downstream is asserted
    if (actual !== exp[axis]) {
      console.error(`${name}: ${axis} is ${actual}, manifest declares ${exp[axis]}`);
      failures++;
    }
  }
}
if (failures) { console.error('SELF-CHECK FAILED'); process.exit(1); }

mkdirSync('out', { recursive: true });
for (const [name, env] of Object.entries(fixtures)) {
  writeFileSync(`out/${name}`, JSON.stringify(env, null, 2) + '\n');
}
writeFileSync('out/expected.json', JSON.stringify(expected, null, 2) + '\n');
writeFileSync('out/signer-public-key.txt', SIGNER_PUB + '\n');
writeFileSync('out/mismatched-signer-public-key.txt', MISMATCH_PUB + '\n');
console.log(`\nkid: ${KID}`);
console.log(`chain head (02, s5.7 envelope hash): ${envelopeHash(r02)}`);
console.log(`wrote ${Object.keys(fixtures).length} fixtures + expected.json + 2 public keys to out/`);
